#!/usr/bin/env python3
# R1 self-parse: mechanically adapt the REAL subrust lexer (../src/lex.rs) into
# a standalone subrust program (self/lex.rs) that subrust itself checks and runs.
# The lex() logic is VERBATIM; the only adaptation applied is:
#   - `///`/`//!` doc comments -> plain `//` (doc comments intentionally rejected)
# Everything else — the real `fn lex(src: &str)` signature, `src.len()`,
# `let b = src.as_bytes()`, `const TOK_NONE: Tok = …`, and the unannotated
# `let mut i = 0` loop counters (integer inference now fixes them to usize) —
# is carried through unchanged.
# Plus a minimal Mem/Tok/Diag scaffold with a 256-token pool (the real 16 384
# pool overflows subrust's frame) and a main() that lexes a sample + prints.
import re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
lex = open(os.path.join(HERE, "..", "src", "lex.rs")).read().splitlines()
start = next(i for i, l in enumerate(lex) if l.startswith("pub const T_EOF"))
lex_start = next(i for i, l in enumerate(lex) if l.startswith("pub fn lex(src"))
depth = 0; end = None
for i in range(lex_start, len(lex)):
    depth += lex[i].count("{") - lex[i].count("}")
    if depth == 0 and i > lex_start:
        end = i; break
body = "\n".join(lex[start:end + 1])
body = re.sub(r"^(\s*)//[/!]", r"\1//", body, flags=re.M)

SCAFFOLD = """// GENERATED by self/generate_lex.py — do not edit by hand.
// R1 self-parse: the REAL subrust lexer (src/lex.rs) adapted to run ON subrust.
const E_UNEXPECTED_CHAR: u16 = 0x0101;
const E_UNTERMINATED_STRING: u16 = 0x0102;
const E_BAD_ESCAPE: u16 = 0x0103;
const E_UNTERMINATED_COMMENT: u16 = 0x0104;
const E_DOC_COMMENT: u16 = 0x0105;
const E_BAD_NUMBER: u16 = 0x0106;
const E_BAD_SUFFIX: u16 = 0x0107;
const E_CHAR_LITERAL: u16 = 0x0108;
const E_NON_ASCII: u16 = 0x0109;
const E_STR_TOO_LONG: u16 = 0x010A;
const E_SRC_TOO_BIG: u16 = 0x0001;
const E_TOKEN_TOO_LONG: u16 = 0x0004;
const SRC_MAX: usize = 16777216;
const CAP_TOKS: usize = 256;
const CAP_DIAGS: usize = 16;
#[derive(Clone, Copy)]
struct Diag { code: u16, lo: u32, hi: u32, a: u32, b: u32 }

"""
MEM = """
#[derive(Clone, Copy)]
struct Mem { toks: [Tok; CAP_TOKS], tok_n: usize, diags: [Diag; CAP_DIAGS], diag_n: usize }
impl Mem {
    fn reset(&mut self) { self.tok_n = 0; self.diag_n = 0; }
    fn diag(&mut self, code: u16, lo: u32, hi: u32, a: u32, b: u32) {
        if self.diag_n < CAP_DIAGS {
            self.diags[self.diag_n] = Diag { code: code, lo: lo, hi: hi, a: a, b: b };
            self.diag_n += 1;
        }
    }
    fn push_tok(&mut self, t: Tok) {
        if self.tok_n < CAP_TOKS { self.toks[self.tok_n] = t; self.tok_n += 1; }
    }
}
fn main() {
    // the real `fn lex(src: &str)` signature, driven by a &str literal
    let src = "fn add(a: i64) -> i64 { let x = 0xFF; return a == x <= 1; } // done";
    let mut m = Mem {
        toks: [Tok { kind: 0, len: 0, pos: 0 }; CAP_TOKS], tok_n: 0,
        diags: [Diag { code: 0, lo: 0, hi: 0, a: 0, b: 0 }; CAP_DIAGS], diag_n: 0,
    };
    let ok = lex(src, &mut m);
    print_bool(ok);
    print_usize(m.tok_n);
    print_usize(m.diag_n);
    let mut i: usize = 0;
    while i < m.tok_n {
        let t = m.toks[i];
        print_i64(t.kind as i64); print_i64(t.pos as i64); print_i64(t.len as i64);
        i += 1;
    }
}
"""
open(os.path.join(HERE, "lex.rs"), "w").write(SCAFFOLD + body + "\n" + MEM)
print("wrote self/lex.rs (lexer body from src lines %d-%d)" % (start + 1, end + 1))
