#!/usr/bin/env python3
# R2 self-check / R3 self-run: mechanically adapt the REAL subrust lexer
# (../src/lex.rs) AND parser (../src/parse.rs) into a single standalone subrust
# program (self/parse.rs) that subrust itself checks and runs — lexing then
# parsing a sample and reporting the item/node/diag counts.
#
# Like generate_lex.py, the lex()/parse() logic is VERBATIM but for two rewrites:
#   - `///`/`//!` doc comments -> plain `//` (doc comments intentionally rejected)
#   - tok_is's body is inlined to compare `src.as_bytes()` bytes directly,
#     because its real body calls `ast::tok_text(src,t).as_bytes()` and tok_text
#     returns `&src[lo..hi]` — a `&str` sub-slice subrust cannot yet produce, and
#     returning a `&[u8]` from a helper hits the ref-escape guard. The inlined
#     form (byte index + compare) is removable once `&str` is a fat pointer.
# The AST constants (N_*/OP_*/FLAG_*/DERIVE_*), the Node struct + nd(), and the
# error codes are lifted from ../src/ast.rs and ../src/diag.rs unchanged; only
# the Mem pool (toks + nodes + diags) is a small hand-written scaffold, because
# the real 16 384-node pool overflows subrust's 1024-slot frame cap.
import re, os

HERE = os.path.dirname(os.path.abspath(__file__))


def read(name):
    return open(os.path.join(HERE, "..", "src", name)).read()


def strip_docs(s):
    return re.sub(r"^(\s*)//[/!]", r"\1//", s, flags=re.M)


def span(lines, start_pred, brace_from=None):
    """Return lines[start .. matching-brace-end] as a string. If brace_from is
    None, start_pred marks a single starting line and we go to EOF."""
    start = next(i for i, l in enumerate(lines) if start_pred(l))
    if brace_from is None:
        return "\n".join(lines[start:])
    fn_start = next(i for i, l in enumerate(lines) if brace_from(l))
    depth = 0
    for i in range(fn_start, len(lines)):
        depth += lines[i].count("{") - lines[i].count("}")
        if depth == 0 and i > fn_start:
            return "\n".join(lines[start:i + 1])
    raise RuntimeError("unterminated block")


ast = read("ast.rs").splitlines()
lex = read("lex.rs").splitlines()
parse = read("parse.rs").splitlines()
diag = read("diag.rs")

# --- error codes used by the lexer, parser, and pool overflow ---
ecodes = "\n".join(re.findall(r"^pub const E_[A-Z_0-9]+: u16 = 0x[0-9A-Fa-f]+;", diag, re.M))

# --- AST constants (NODE_NIL, N_*, OP_*, FLAG_*, DERIVE_*) + Node + nd() ---
ast_start = next(i for i, l in enumerate(ast) if l.startswith("pub const NODE_NIL"))
ast_end = next(i for i, l in enumerate(ast) if l.startswith("pub fn nd("))
adepth = 0
for i in range(ast_end, len(ast)):
    adepth += ast[i].count("{") - ast[i].count("}")
    if adepth == 0 and i > ast_end:
        ast_end = i
        break
ast_block = strip_docs("\n".join(ast[ast_start:ast_end + 1]))

# --- lexer body: `pub const T_EOF` .. end of lex() ---
lex_body = strip_docs(span(lex, lambda l: l.startswith("pub const T_EOF"),
                           lambda l: l.startswith("pub fn lex(src")))

# --- parser body: `pub const PARSE_DEPTH_CAP` .. EOF ---
parse_body = strip_docs(span(parse, lambda l: l.startswith("pub const PARSE_DEPTH_CAP")))
# `&str` is not a sliceable fat pointer yet, and a `&[u8]`-returning helper would
# hit the ref-escape guard; inline tok_is's comparison over `src.as_bytes()`.
TOK_IS_REAL = """fn tok_is(src: &str, mem: &Mem, ti: u32, s: &[u8]) -> bool {
    let t = mem.tok(ti);
    let b = tok_text(src, t).as_bytes();
    bytes_eq_pub(b, s)
}"""
TOK_IS_INLINE = """fn tok_is(src: &str, mem: &Mem, ti: u32, s: &[u8]) -> bool {
    let t = mem.tok(ti);
    let b = src.as_bytes();
    let lo = t.pos as usize;
    if t.len as usize != s.len() { return false; }
    let mut i: usize = 0;
    while i < s.len() {
        if lo + i >= b.len() || b[lo + i] != s[i] { return false; }
        i += 1;
    }
    true
}"""
assert TOK_IS_REAL in parse_body, "tok_is source drifted; update the generator"
parse_body = parse_body.replace(TOK_IS_REAL, TOK_IS_INLINE)

SCAFFOLD = """// GENERATED by self/generate_parse.py — do not edit by hand.
// R2/R3 self-host: the REAL subrust lexer + parser (src/lex.rs, src/parse.rs)
// adapted to run ON subrust: lex then parse a sample, report item/node counts.
// Small pools: the interpreted Mem is a stack local in main(), so toks+nodes
// must fit subrust's 1024-slot frame cap (a Node is 10 slots). Sized for the
// sample, not a real program — this is the R2/R3 harness, not a deployment.
const SRC_MAX: usize = 16777216;
const CAP_TOKS: usize = 48;
const CAP_NODES: usize = 40;
const CAP_DIAGS: usize = 8;
"""

MEM = """
#[derive(Clone, Copy)]
struct Diag { code: u16, lo: u32, hi: u32, a: u32, b: u32 }
#[derive(Clone, Copy)]
struct Mem {
    toks: [Tok; CAP_TOKS], tok_n: usize,
    nodes: [Node; CAP_NODES], node_n: usize,
    diags: [Diag; CAP_DIAGS], diag_n: usize,
    overflow: bool,
    root_first: u32, root_n: u32,
}
impl Mem {
    fn reset(&mut self) {
        self.tok_n = 0; self.node_n = 0; self.diag_n = 0;
        self.overflow = false; self.root_first = NODE_NIL; self.root_n = 0;
    }
    fn diag(&mut self, code: u16, lo: u32, hi: u32, a: u32, b: u32) {
        if self.diag_n < CAP_DIAGS {
            self.diags[self.diag_n] = Diag { code: code, lo: lo, hi: hi, a: a, b: b };
            self.diag_n += 1;
        }
    }
    fn push_tok(&mut self, t: Tok) {
        if self.tok_n >= CAP_TOKS {
            if !self.overflow { self.overflow = true; self.diag(E_TOO_MANY_TOKENS, t.pos, t.pos, 0, 0); }
            return;
        }
        self.toks[self.tok_n] = t;
        self.tok_n += 1;
    }
    fn tok(&self, i: u32) -> Tok {
        let i = i as usize;
        if i < self.tok_n { self.toks[i] } else { TOK_NONE }
    }
    fn push_node(&mut self, n: Node) -> u32 {
        if self.node_n >= CAP_NODES {
            if !self.overflow { self.overflow = true; self.diag(E_TOO_MANY_NODES, n.lo, n.hi, 0, 0); }
            return NODE_NIL;
        }
        self.nodes[self.node_n] = n;
        self.node_n += 1;
        (self.node_n - 1) as u32
    }
    fn node(&self, i: u32) -> Node {
        let i = i as usize;
        if i < self.node_n { self.nodes[i] } else { NODE_NONE }
    }
    fn set_link(&mut self, i: u32, link: u32) {
        let i = i as usize;
        if i < self.node_n { self.nodes[i].link = link; }
    }
}
fn main() {
    // exercises items, params, ref type, if/else, comparison, unary, blocks
    let src = "fn f(x: i64) -> i64 { if x > 0 { x } else { 0 - x } }";
    let mut m = Mem {
        toks: [TOK_NONE; CAP_TOKS], tok_n: 0,
        nodes: [NODE_NONE; CAP_NODES], node_n: 0,
        diags: [Diag { code: 0, lo: 0, hi: 0, a: 0, b: 0 }; CAP_DIAGS], diag_n: 0,
        overflow: false,
        root_first: NODE_NIL, root_n: 0,
    };
    let lexed = lex(src, &mut m);
    print_bool(lexed);
    print_usize(m.tok_n);
    let ok = parse(src, &mut m);
    print_bool(ok);
    print_usize(m.diag_n);
    print_usize(m.node_n);
    print_i64(m.root_n as i64);
    // walk the top-level item chain, printing each item's node kind
    let mut it = m.root_first;
    while it != NODE_NIL {
        let n = m.node(it);
        print_i64(n.kind as i64);
        it = n.link;
    }
}
"""

out = SCAFFOLD + ecodes + "\n\n" + ast_block + "\n" + MEM + "\n" + lex_body + "\n" + parse_body + "\n"
open(os.path.join(HERE, "parse.rs"), "w").write(out)
print("wrote self/parse.rs (%d bytes)" % len(out))
